version: '3.7'
services:
  elk-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELK_VERSION
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es_net
  elk-kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    environment:
        SERVER_NAME: kibana.local
        ELASTICSEARCH_HOSTS: '["http://elk-elasticsearch:9200"]'
    ports:
        - "5601:5601"
    networks:
        - es_net
    depends_on:
        - elk-elasticsearch

  elk-logstash:
    image: docker.elastic.co/logstash/logstash:$ELK_VERSION
    container_name: logstash
    environment:
        SERVER_NAME: logstash.local
    ports:
        - "5000:5000"
        - "9600:9600"
    networks:
        - es_net
    healthcheck:
        test: bin/logstash -t
        interval: 60s
        timeout: 50s
        retries: 5

networks:
    es_net:
        name: es_net
        driver: bridge