version: '3.7'
services:
  es-logstash:
    image: docker.elastic.co/logstash/logstash:$ELK_VERSION
    container_name: logstash
    environment:
        SERVER_NAME: logstash.local
    ports:
        - "5000:5000"
        - "9600:9600"
    networks:
        - es_net
    healthcheck:
        test: bin/logstash -t
        interval: 60s
        timeout: 50s
        retries: 5

networks:
    es_net:
        external: true
